<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: rpc in /www/site_agent_sdkmanage/src/App/Logics/SDKManage/Merchant/LogicMerchantPaymentID.php on line <i>88</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>370088</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/www/site_agent_sdkmanage/public/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.2530</td><td bgcolor='#eeeeec' align='right'>4276872</td><td bgcolor='#eeeeec'>App\Http\Kernel->handle(  )</td><td title='/www/site_agent_sdkmanage/public/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.2593</td><td bgcolor='#eeeeec' align='right'>4335208</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\Kernel->exec(  )</td><td title='/www/site_agent_sdkmanage/src/App/Http/Kernel.php' bgcolor='#eeeeec'>.../Kernel.php<b>:</b>56</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.2594</td><td bgcolor='#eeeeec' align='right'>4339064</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\Kernel->_exec(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/Kernel.php' bgcolor='#eeeeec'>.../Kernel.php<b>:</b>112</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2598</td><td bgcolor='#eeeeec' align='right'>4357336</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\RPCService->callFunction(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/Kernel.php' bgcolor='#eeeeec'>.../Kernel.php<b>:</b>167</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2598</td><td bgcolor='#eeeeec' align='right'>4358032</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\RPCService->Pluto\Foundation\RPC\{closure}(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/RPCService.php' bgcolor='#eeeeec'>.../RPCService.php<b>:</b>134</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2650</td><td bgcolor='#eeeeec' align='right'>4362592</td><td bgcolor='#eeeeec'>miniPayCenter\RPC\MiddleWare\ServiceEnableMiddleWare->handle(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/RPCService.php' bgcolor='#eeeeec'>.../RPCService.php<b>:</b>180</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2651</td><td bgcolor='#eeeeec' align='right'>4363328</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\RPCService->Pluto\Foundation\RPC\{closure}(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/MiddleWare/ServiceEnableMiddleWare.php' bgcolor='#eeeeec'>.../ServiceEnableMiddleWare.php<b>:</b>23</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2652</td><td bgcolor='#eeeeec' align='right'>4364464</td><td bgcolor='#eeeeec'>miniPayCenter\RPC\MiddleWare\SecretMiddleWare->handle(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/RPCService.php' bgcolor='#eeeeec'>.../RPCService.php<b>:</b>180</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2652</td><td bgcolor='#eeeeec' align='right'>4365296</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\RPCService->Pluto\Foundation\RPC\{closure}(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/MiddleWare/SecretMiddleWare.php' bgcolor='#eeeeec'>.../SecretMiddleWare.php<b>:</b>51</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.2653</td><td bgcolor='#eeeeec' align='right'>4366432</td><td bgcolor='#eeeeec'>App\RPC\MiddleWare\TokenMiddleWare->handle(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/RPCService.php' bgcolor='#eeeeec'>.../RPCService.php<b>:</b>180</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2799</td><td bgcolor='#eeeeec' align='right'>4501120</td><td bgcolor='#eeeeec'>Pluto\Foundation\RPC\RPCService->Pluto\Foundation\RPC\{closure}(  )</td><td title='/www/site_agent_sdkmanage/src/App/RPC/MiddleWare/TokenMiddleWare.php' bgcolor='#eeeeec'>.../TokenMiddleWare.php<b>:</b>56</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.2801</td><td bgcolor='#eeeeec' align='right'>4513688</td><td bgcolor='#eeeeec'>hellaEngine\support\Reflection\Reflection::callClassFuncNamedObjectArray(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/pluto-engine/core/src/Pluto/Foundation/RPC/RPCService.php' bgcolor='#eeeeec'>.../RPCService.php<b>:</b>153</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.3537</td><td bgcolor='#eeeeec' align='right'>5872640</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/www/site-agent-sdkmanage/src/vendor/hella-engine/support/src/hellaEngine/support/Reflection/Reflection.php:90}' target='_new'>call_user_func_array:{/www/site_agent_sdkmanage/src/vendor/hella-engine/support/src/hellaEngine/support/Reflection/Reflection.php:90}</a>
(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/hella-engine/support/src/hellaEngine/support/Reflection/Reflection.php' bgcolor='#eeeeec'>.../Reflection.php<b>:</b>90</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>0.3537</td><td bgcolor='#eeeeec' align='right'>5873096</td><td bgcolor='#eeeeec'>miniPayCenter\RPC\ReflectionRPC->Add(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/hella-engine/support/src/hellaEngine/support/Reflection/Reflection.php' bgcolor='#eeeeec'>.../Reflection.php<b>:</b>90</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>0.3537</td><td bgcolor='#eeeeec' align='right'>5873472</td><td bgcolor='#eeeeec'>miniPayCenter\RPC\ReflectionRPC->__call(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/hella-engine/support/src/hellaEngine/support/Reflection/Reflection.php' bgcolor='#eeeeec'>.../Reflection.php<b>:</b>90</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>17</td><td bgcolor='#eeeeec' align='center'>0.3538</td><td bgcolor='#eeeeec' align='right'>5873848</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/www/site-agent-sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/ReflectionRPC.php:45}' target='_new'>call_user_func_array:{/www/site_agent_sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/ReflectionRPC.php:45}</a>
(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/ReflectionRPC.php' bgcolor='#eeeeec'>.../ReflectionRPC.php<b>:</b>45</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>18</td><td bgcolor='#eeeeec' align='center'>0.3538</td><td bgcolor='#eeeeec' align='right'>5874304</td><td bgcolor='#eeeeec'>App\Logics\SDKManage\Merchant\LogicMerchantPaymentID->Add(  )</td><td title='/www/site_agent_sdkmanage/src/vendor/minipay-center/supports/src/miniPayCenter/RPC/ReflectionRPC.php' bgcolor='#eeeeec'>.../ReflectionRPC.php<b>:</b>45</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>19</td><td bgcolor='#eeeeec' align='center'>0.3549</td><td bgcolor='#eeeeec' align='right'>5875976</td><td bgcolor='#eeeeec'>App\Logics\SDKManage\Merchant\LogicMerchantPaymentID->DoAdd(  )</td><td title='/www/site_agent_sdkmanage/src/App/CodeTemplates/Logics/LogicSDKManageMerchantPaymentIDAdd.php' bgcolor='#eeeeec'>.../LogicSDKManageMerchantPaymentIDAdd.php<b>:</b>50</td></tr>
</table></font>
{"succ":false,"code":0,"data":{"trace":["\/www\/site_agent_sdkmanage\/src\/App\/Logics\/SDKManage\/Merchant\/LogicMerchantPaymentID.php(88):Call to a member function getRetData() on null","\/www\/site_agent_sdkmanage\/src\/App\/CodeTemplates\/Logics\/LogicSDKManageMerchantPaymentIDAdd.php(50):App\\Logics\\SDKManage\\Merchant\\LogicMerchantPaymentID->DoAdd","[internal function]:App\\Logics\\SDKManage\\Merchant\\LogicMerchantPaymentID->Add","\/www\/site_agent_sdkmanage\/src\/vendor\/minipay-center\/supports\/src\/miniPayCenter\/RPC\/ReflectionRPC.php(45):call_user_func_array","[internal function]:miniPayCenter\\RPC\\ReflectionRPC->__call","\/www\/site_agent_sdkmanage\/src\/vendor\/hella-engine\/support\/src\/hellaEngine\/support\/Reflection\/Reflection.php(90):call_user_func_array","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/RPCService.php(153):hellaEngine\\support\\Reflection\\Reflection::callClassFuncNamedObjectArray","\/www\/site_agent_sdkmanage\/src\/App\/RPC\/MiddleWare\/TokenMiddleWare.php(56):Pluto\\Foundation\\RPC\\RPCService->Pluto\\Foundation\\RPC\\{closure}","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/RPCService.php(180):App\\RPC\\MiddleWare\\TokenMiddleWare->handle","\/www\/site_agent_sdkmanage\/src\/vendor\/minipay-center\/supports\/src\/miniPayCenter\/RPC\/MiddleWare\/SecretMiddleWare.php(51):Pluto\\Foundation\\RPC\\RPCService->Pluto\\Foundation\\RPC\\{closure}","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/RPCService.php(180):miniPayCenter\\RPC\\MiddleWare\\SecretMiddleWare->handle","\/www\/site_agent_sdkmanage\/src\/vendor\/minipay-center\/supports\/src\/miniPayCenter\/RPC\/MiddleWare\/ServiceEnableMiddleWare.php(23):Pluto\\Foundation\\RPC\\RPCService->Pluto\\Foundation\\RPC\\{closure}","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/RPCService.php(180):miniPayCenter\\RPC\\MiddleWare\\ServiceEnableMiddleWare->handle","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/RPCService.php(134):Pluto\\Foundation\\RPC\\RPCService->Pluto\\Foundation\\RPC\\{closure}","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/Kernel.php(167):Pluto\\Foundation\\RPC\\RPCService->callFunction","\/www\/site_agent_sdkmanage\/src\/vendor\/pluto-engine\/core\/src\/Pluto\/Foundation\/RPC\/Kernel.php(112):Pluto\\Foundation\\RPC\\Kernel->_exec","\/www\/site_agent_sdkmanage\/src\/App\/Http\/Kernel.php(56):Pluto\\Foundation\\RPC\\Kernel->exec","\/www\/site_agent_sdkmanage\/public\/index.php(18):App\\Http\\Kernel->handle"]},"description":"SystemError","command_name":"\/sdkmanage\/merchant\/payment_id\/add"}