#!/usr/bin/env php
<?php
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}
foreach (array(__DIR__ . '/../../../autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {

        define('ZEUS_COMPOSER_INSTALL', $file);
        break;
    }
}

require ZEUS_COMPOSER_INSTALL;

$app = new \ZeusConsole\ConsoleAppMiniPay ();
$app->run();
