SVNUserName: zhipeng
SVNPassWord: zhipeng001
MakeClass.DBSExportPath: /Users/peng.zhi/Documents/Object/one_roll/one_roll_server/include/dbs/templates
MakeClass.DBSTemplatePath: /Users/peng.zhi/Documents/Object/one_roll/one_roll_server/DBTemplates
